/**
 * Full preset - All color types and functions
 */

import type { BundlePreset } from "./types";

export const full: BundlePreset = {
  name: "Full",
  description: "All color types and functions",
  types: [
    "hex-color",
    "rgb-color",
    "hsl-color",
    "hsv-color",
    "hwb-color",
    "oklch-color",
    "oklab-color",
    "okhsl-color",
    "okhsv-color",
    "lab-color",
    "lch-color",
    "p3-color",
    "p3-linear-color",
    "srgb-color",
    "srgb-linear-color",
    "xyz-d50-color",
    "xyz-d65-color",
    "css-color",
  ],
  functions: [
    "adjust_chroma",
    "adjust_hue",
    "adjust_lightness",
    "adjust_to_contrast",
    "alpha_blend",
    "alpha_scale",
    "analogous",
    "apca_contrast",
    "are_similar",
    "auto_text_color",
    "best_contrast",
    "chroma",
    "clamp_chroma",
    "clamp_lightness",
    "clamp_to_gamut",
    "complement",
    "contrast_ratio",
    "cooler",
    "darken",
    "delta_e_76",
    "delta_e_2000",
    "delta_e_ok",
    "desaturate",
    "distributed",
    "diverging",
    "grayscale",
    "harmonize",
    "hue",
    "hue_difference",
    "in_gamut",
    "interpolate",
    "invert",
    "is_cool",
    "is_dark",
    "is_light",
    "is_neutral",
    "is_warm",
    "lighten",
    "lightness",
    "luminance",
    "meets_contrast",
    "mix",
    "monochromatic",
    "muted",
    "neutral_variant",
    "relative_luminance",
    "rotate_hue",
    "saturate",
    "scale_chroma",
    "scale_lightness",
    "sepia",
    "set_chroma",
    "set_hue",
    "set_lightness",
    "shade_scale",
    "split_complement",
    "steps",
    "tetradic",
    "tint_scale",
    "to_gamut",
    "triadic",
    "vibrant",
    "warmer",
    "wcag_level",
  ],
};
