/**
 * Generate JavaScript output for bundled schemas
 */

import type { BundledSchemaEntry } from "@/bundler/selective-bundler.js";

export interface OutputGeneratorOptions {
  schemas: BundledSchemaEntry[];
  includeHelper?: boolean; // Include makeConfig() helper
  generatedBy?: string; // CLI command used to generate
}

/**
 * Generate JavaScript code for bundled schemas
 */
export function generateOutput(options: OutputGeneratorOptions): string {
  const { schemas, includeHelper = true } = options;

  const timestamp = new Date().toISOString();
  const schemaList = schemas.map((s) => s.uri).join(", ");

  const lines: string[] = [];

  // Header comment
  lines.push("// Auto-generated by @tokens-studio/tokenscript-schemas");
  if (options.generatedBy) {
    lines.push(`// Command: ${options.generatedBy}`);
  }
  lines.push(`// Generated: ${timestamp}`);
  lines.push(`// Schemas: ${schemaList}`);
  lines.push("");

  // Import statement
  lines.push('import { Config } from "@tokens-studio/tokenscript-interpreter";');
  lines.push("");

  // SCHEMAS export
  lines.push("export const SCHEMAS = [");
  for (const entry of schemas) {
    // Format each schema entry - we need to serialize both uri and schema
    const schemaJson = JSON.stringify(entry.schema, null, 2);
    const uriJson = JSON.stringify(entry.uri);

    // Indent the schema JSON
    const indentedSchema = schemaJson
      .split("\n")
      .map((line) => `    ${line}`)
      .join("\n");

    lines.push(`  {`);
    lines.push(`    uri: ${uriJson},`);
    lines.push(`    schema: ${indentedSchema.trim()}`);
    lines.push(`  },`);
  }
  lines.push("];");
  lines.push("");

  // Helper function
  if (includeHelper) {
    lines.push("export function makeConfig() {");
    lines.push("  return new Config().registerSchemas(SCHEMAS);");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}
