import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { expandPresetSchemas } from "@/bundler/presets/index.js";
import { bundleSchemas } from "./bundle.js";

// Mock ulog to silence logs during tests
vi.mock("ulog", () => {
  const mockLogger = () => {};
  mockLogger.error = () => {};
  mockLogger.warn = () => {};
  mockLogger.info = () => {};
  mockLogger.log = () => {};
  mockLogger.debug = () => {};
  mockLogger.trace = () => {};

  return {
    default: () => mockLogger,
  };
});

describe("Bundle Command", () => {
  it("should bundle schemas and return output", async () => {
    const result = await bundleSchemas(["hex-color"]);

    expect(result.output).toContain("export const SCHEMAS");
    expect(result.output).toContain("export function makeConfig()");
    expect(result.output).toContain("hex-color");
    expect(result.metadata.requestedSchemas).toEqual(["hex-color"]);
  });

  it("should bundle multiple schemas with dependencies", async () => {
    const result = await bundleSchemas(["function:adjust_chroma"]);

    expect(result.output).toContain("SCHEMAS");
    expect(result.metadata.requestedSchemas).toEqual(["function:adjust_chroma"]);

    // adjust_chroma requires srgb-color and oklch-color
    // With includeColorTypeDependencies, this pulls in all conversion dependencies
    expect(result.metadata.resolvedDependencies.length).toBeGreaterThanOrEqual(3);
    expect(result.metadata.resolvedDependencies).toContain("adjust_chroma");
    expect(result.metadata.resolvedDependencies).toContain("srgb-color");
    expect(result.metadata.resolvedDependencies).toContain("oklch-color");
  });

  it("should bundle function schemas", async () => {
    const result = await bundleSchemas(["function:invert"]);

    expect(result.output).toContain("SCHEMAS");
    expect(result.output).toContain("/function/invert/");
    expect(result.metadata.requestedSchemas).toEqual(["function:invert"]);
  });

  it("should include auto-generated header comment", async () => {
    const result = await bundleSchemas(["hex-color"]);

    expect(result.output).toContain("Auto-generated by @tokens-studio/tokenscript-schemas");
    expect(result.output).toContain("Generated:");
  });

  describe("Presets", () => {
    it("should expand preset:css to schema list", () => {
      const result = expandPresetSchemas(["preset:css"]);

      expect(result).toContain("type:hex-color");
      expect(result).toContain("type:rgb-color");
      expect(result).toContain("type:hsl-color");
      expect(result).toContain("type:oklch-color");
      expect(result).toContain("type:css-color");
      expect(result).toContain("function:lighten");
      expect(result).toContain("function:darken");
      expect(result.length).toBeGreaterThan(5);
    });

    it("should combine presets with specific schemas", () => {
      const result = expandPresetSchemas(["preset:css", "type:lab-color"]);

      expect(result).toContain("type:hex-color");
      expect(result).toContain("type:lab-color");
    });

    it("should handle unknown preset gracefully", () => {
      const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});

      const result = expandPresetSchemas(["preset:unknown"]);

      expect(result).toEqual([]);
      expect(warnSpy).toHaveBeenCalledWith("⚠ Unknown preset: unknown");

      warnSpy.mockRestore();
    });
  });

  describe("Custom Schema Directory", () => {
    const customSchemasDir = join(process.cwd(), "test-custom-schemas");
    const customTypeDir = join(customSchemasDir, "types", "custom-color");

    beforeAll(async () => {
      // Create custom schema directory structure
      await mkdir(customTypeDir, { recursive: true });

      // Create a custom schema.json
      const schemaJson = {
        name: "CustomColor",
        type: "color" as const,
        description: "A custom color type for testing",
        slug: "custom-color",
        schema: {
          type: "object" as const,
          properties: {
            x: { type: "number" as const },
            y: { type: "number" as const },
          },
          required: ["x", "y"],
          additionalProperties: false,
        },
        initializers: [
          {
            keyword: "customcolor",
            script: {
              type: "https://schema.tokenscript.dev.gcp.tokens.studio/api/v1/core/tokenscript/0/",
              script: "./custom-initializer.tokenscript",
            },
          },
        ],
        conversions: [] as any[],
      };

      await writeFile(
        join(customTypeDir, "schema.json"),
        JSON.stringify(schemaJson, null, 2),
        "utf-8",
      );

      // Create a custom initializer script
      const initializerScript = `
variable x_val: Number = args.get(0);
variable y_val: Number = args.get(1);
variable result: Color.CustomColor = (x: x_val, y: y_val);
result
      `.trim();

      await writeFile(join(customTypeDir, "custom-initializer.tokenscript"), initializerScript);
    });

    afterAll(async () => {
      // Clean up custom schemas directory
      try {
        await rm(customSchemasDir, { recursive: true, force: true });
      } catch {
        // Ignore if directory doesn't exist
      }
    });

    it("should bundle schemas from custom directory", async () => {
      const result = await bundleSchemas(["type:custom-color"], customSchemasDir);

      expect(result.output).toContain("SCHEMAS");
      expect(result.output).toContain("custom-color");
      expect(result.metadata.requestedSchemas).toEqual(["type:custom-color"]);
      expect(result.metadata.resolvedDependencies).toContain("custom-color");
    });

    it("should include custom schema in output", async () => {
      const result = await bundleSchemas(["custom-color"], customSchemasDir);

      // Verify the output contains the custom schema definition
      expect(result.output).toContain("CustomColor");
      expect(result.output).toContain("customcolor");
      expect(result.output).toContain("A custom color type for testing");
    });

    it("should use custom directory metadata in output", async () => {
      const cliArgs = ["type:custom-color", "--schemas-dir", customSchemasDir];
      const result = await bundleSchemas(["type:custom-color"], customSchemasDir, cliArgs);

      expect(result.metadata.generatedBy).toContain("--schemas-dir");
      expect(result.metadata.generatedBy).toContain(customSchemasDir);
    });

    it("should fail gracefully when schema not found in custom directory", async () => {
      await expect(bundleSchemas(["type:nonexistent-schema"], customSchemasDir)).rejects.toThrow();
    });
  });
});
