import { describe, expect, it, vi } from "vitest";
import { bundleSchemas } from "./bundle.js";

// Mock ulog to silence logs during tests
vi.mock("ulog", () => {
  const mockLogger = () => {};
  mockLogger.error = () => {};
  mockLogger.warn = () => {};
  mockLogger.info = () => {};
  mockLogger.log = () => {};
  mockLogger.debug = () => {};
  mockLogger.trace = () => {};

  return {
    default: () => mockLogger,
  };
});

describe("Bundle Command", () => {
  it("should bundle schemas and return output", async () => {
    const result = await bundleSchemas(["hex-color"]);

    expect(result.output).toContain("export const SCHEMAS");
    expect(result.output).toContain("export function makeConfig()");
    expect(result.output).toContain("hex-color");
    expect(result.metadata.requestedSchemas).toEqual(["hex-color"]);
  });

  it("should bundle multiple schemas with dependencies", async () => {
    const result = await bundleSchemas(["function:adjust_chroma"]);

    expect(result.output).toContain("SCHEMAS");
    expect(result.metadata.requestedSchemas).toEqual(["function:adjust_chroma"]);

    // adjust_chroma requires srgb-color and oklch-color
    // With includeColorTypeDependencies, this pulls in all conversion dependencies
    expect(result.metadata.resolvedDependencies.length).toBeGreaterThanOrEqual(3);
    expect(result.metadata.resolvedDependencies).toContain("adjust_chroma");
    expect(result.metadata.resolvedDependencies).toContain("srgb-color");
    expect(result.metadata.resolvedDependencies).toContain("oklch-color");
  });

  it("should bundle function schemas", async () => {
    const result = await bundleSchemas(["function:invert"]);

    expect(result.output).toContain("SCHEMAS");
    expect(result.output).toContain("/function/invert/");
    expect(result.metadata.requestedSchemas).toEqual(["function:invert"]);
  });

  it("should include auto-generated header comment", async () => {
    const result = await bundleSchemas(["hex-color"]);

    expect(result.output).toContain("Auto-generated by @tokens-studio/tokenscript-schemas");
    expect(result.output).toContain("Generated:");
  });
});
